services:
  ilvecchioforno_api:
    env_file: ".env.dev"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__IlVecchioFornoContext=Host=ilvecchioforno_db;Port=5432;Username=${DB_USER};Password=${DB_PASSWORD};Database=${DB_NAME}
    ports:
      - "8080:8080"
      - "8081:8081"

  ilvecchioforno_db:
    env_file: ".env.dev"
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}

  ilvecchioforno_pgadmin:
    container_name: ilvecchioforno_pgadmin
    image: dpage/pgadmin4:latest
    restart: always
    env_file: ".env.dev"
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWORD}
    ports:
      - "5431:80"
    depends_on:
      - ilvecchioforno_db
    networks:
      - ilvecchioforno_net