name: postgres

services:
  ilvecchioforno.api:
    image: ilvecchioforno.api
    build:
      context: .
      dockerfile: src/IlVecchioForno.API/Dockerfile
  postgres_db:
    container_name: postgres_db
    image: postgres:18.1
    restart: always
    env_file: ".env"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_vol:/var/lib/postgresql
    ports:
      - target: 5432
        published: 5432
        protocol: tcp
        mode: host

volumes:
  postgres_vol:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/${USER}/databases/postgresql
