// <auto-generated />
using System;
using IlVecchioForno.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace IlVecchioForno.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(IlVecchioFornoDbContext))]
    [Migration("20260125131241_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("pizzas_schema")
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("IlVecchioForno.Domain.Ingredients.Ingredient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMPTZ")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("VARCHAR(256)")
                        .HasColumnName("name");

                    b.Property<short?>("QuantityTypeId")
                        .HasColumnType("SMALLINT")
                        .HasColumnName("quantity_type_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TIMESTAMPTZ")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_ingredients");

                    b.HasIndex("QuantityTypeId");

                    b.ToTable("ingredients", "pizzas_schema");
                });

            modelBuilder.Entity("IlVecchioForno.Domain.PizzaIngredients.PizzaIngredient", b =>
                {
                    b.Property<int>("PizzaId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("pizza_id");

                    b.Property<int>("IngredientId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ingredient_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMPTZ")
                        .HasColumnName("created_at");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("NUMERIC(9, 3)")
                        .HasColumnName("quantity");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TIMESTAMPTZ")
                        .HasColumnName("updated_at");

                    b.HasKey("PizzaId", "IngredientId")
                        .HasName("pk_pizzas_ingredients");

                    b.HasIndex("IngredientId");

                    b.ToTable("pizzas_ingredients", "pizzas_schema");
                });

            modelBuilder.Entity("IlVecchioForno.Domain.Pizzas.Pizza", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset?>("ArchivedAt")
                        .HasColumnType("TIMESTAMPTZ")
                        .HasColumnName("archived_at");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMPTZ")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("VARCHAR(1024)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("VARCHAR(256)")
                        .HasColumnName("name");

                    b.Property<decimal>("Price")
                        .HasColumnType("NUMERIC(6, 2)")
                        .HasColumnName("price");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TIMESTAMPTZ")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_pizzas");

                    b.ToTable("pizzas", "pizzas_schema");
                });

            modelBuilder.Entity("IlVecchioForno.Domain.QuantityTypes.QuantityType", b =>
                {
                    b.Property<short>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("SMALLINT")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<short>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMPTZ")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("VARCHAR(256)")
                        .HasColumnName("name");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("VARCHAR(4)")
                        .HasColumnName("unit");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TIMESTAMPTZ")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_quantity_types");

                    b.ToTable("quantity_types", "pizzas_schema");
                });

            modelBuilder.Entity("IlVecchioForno.Domain.Ingredients.Ingredient", b =>
                {
                    b.HasOne("IlVecchioForno.Domain.QuantityTypes.QuantityType", "QuantityType")
                        .WithMany()
                        .HasForeignKey("QuantityTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_ingredients__quantity_types");

                    b.Navigation("QuantityType");
                });

            modelBuilder.Entity("IlVecchioForno.Domain.PizzaIngredients.PizzaIngredient", b =>
                {
                    b.HasOne("IlVecchioForno.Domain.Ingredients.Ingredient", "Ingredient")
                        .WithMany()
                        .HasForeignKey("IngredientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_pizzas_ingredients__ingredients");

                    b.HasOne("IlVecchioForno.Domain.Pizzas.Pizza", null)
                        .WithMany("PizzaIngredients")
                        .HasForeignKey("PizzaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_pizzas_ingredients__pizzas");

                    b.Navigation("Ingredient");
                });

            modelBuilder.Entity("IlVecchioForno.Domain.Pizzas.Pizza", b =>
                {
                    b.Navigation("PizzaIngredients");
                });
#pragma warning restore 612, 618
        }
    }
}
